site_name: QuAntiL
repo_url: https://github.com/UST-QuAntiL/quantil-docs
edit_uri: tree/master/docs
nav:
    - Home: 'index.md'
    - Quickstart: 'developer-guide/docker.md'
    - User Guide:
        - 'QC Atlas': 'user-guide/qc-atlas.md'
        - 'Circuit Transformer': 'user-guide/circuit-transformer.md'
        - 'NISQ Analyzer': 'user-guide/nisq-analyzer.md'
        - 'QProv': 'user-guide/qprov.md'
        - 'QHAna': 'user-guide/qhana.md'
    - Developer Guide:
        - 'IntelliJ Setup': 'developer-guide/intellij.md'
        - 'OpenAPI': 'developer-guide/openapi.md'
        - 'Application Architecture': 'developer-guide/qc-atlas/application-architecture.md'
        - 'Testing': 'developer-guide/qc-atlas/testing.md'
        - 'Database migrations': 'developer-guide/qc-atlas/db-migrations.md'
theme:
    name: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
plugins:
    - include-markdown